### ISSUE TITLE
Setup the structure to work with direct imports

### ISSUE THREAD

**Issue by nikgraf** [draft-js-utils/draft-js-utils#2]
I can imagine that this quickly will grow into an library with many utils while people only need few of them. I suggest we make the structure is done in a way that you directly can import each util like this:

``` js
// just import getEntityRanges without importing the whole library
import getEntityRanges from 'draft-js-utils/getEntityRanges';
```

This way people don't have to get the whole library. With tree-shaking activated it wouldn't matter, but as far as I understood this is not active by default in most webpack/browserify setups.

This is what I consider to be not ideal:

``` js
// import the whole lib and get getEntityRanges
import { getEntityRanges } from 'draft-js-utils';
```

What are you thoughts?

**Comment by johanneslumpe** [comment]
Tree-shaking is a webpack 2 only feature (AFAIK?), whose status is beta. I personally like the 2nd syntax more, but given the fact that we do not want to force people to import the whole library I think the 1st one is fine - just like lodash does it. Potentially we could support both.

What about namespaces? Do we keep all functions at the top level or do we put them into namespaces like `blocks`, `selection` etc.? I think that having them at the top level might be easier for us, because things like `getSelectedBlocks` might do into `blocks` or `selection` and it would make it harder for the consumer to figure out where things are. Lodash removed namespaces because of exactly this issue.

**Comment by nikgraf** [comment]
Yep, we potentially can support both ways, but in readme,examples & docs I we should use only the direct import. People who don't know this just copy&paste what we do in the readme.

I would agree with a flat structure without namespaces.

**Comment by johanneslumpe** [comment]
:+1:

**Comment by sstur** [comment]
I like the idea of supporting both `import {foo} from 'thing'` and `import foo from 'thing/foo'`. I'll make it happen.

**Comment by johanneslumpe** [comment]
@nikgraf @sstur I guess this can be closed now that we have a repo which, as far as I could see, supports both?

**Comment by sstur** [comment]
@johanneslumpe: I'm not sure this is actually fixed. Correct me if I'm misunderstanding the request, but I believe the way to enable `import foo from 'thing/foo'` is to create a file in the root of `thing` named `foo.js` that simply exports `path/to/real/foo.js`. So you end up with a bunch of small shim files. (is there a better way? I feel like npm should have aliases or something)

I'm OK with this if it improves the project, but wondering if it would be better to use lib subfolder, which adds a bit of length: `import foo from 'thing/lib/foo'`

**Comment by johanneslumpe** [comment]
@sstur Oh yeah you're right actually. We'd either have to use said shim files or set up babel so that all the compiled code just ends up in the root folder. Using a `lib` folder is another options of course. I'm not sure which one of these is the "right" way though.

**Comment by sstur** [comment]
Closing this for now. In process of setting up a new monorepo using `lerna` which will have a different structure.
