### ISSUE TITLE
Agree on coding style

### ISSUE THREAD

**Issue by johanneslumpe** [draft-js-utils/draft-js-utils#3]
I like the airbnb eslint config. What are your thoughts on it?

Full disclosure: I like trailing commas and semicolons ;)

**Comment by nikgraf** [comment]
+1 on the default airbnb config. eslint + jscs

**Comment by johanneslumpe** [comment]
@nikgraf What does jscs what eslint does not? (Honest question, I don't know) It seems that it can do more automated fixes?

**Comment by nikgraf** [comment]
@johanneslumpe jscs covers a couple of rules that eslint doesn't have. can't remember which ones specifically and that might be a moving target anyway. the nice thing about it is that airbnb maintains both & keeps them in sync

**Comment by jaaberg** [comment]
+1 for airbnb as well. Personally don't like trailing commas, but that is something I can live with :P

**Comment by sstur** [comment]
This repo uses the coding style from Facebook. It's not just this way because draft-js is from FB but because I learned this style working at FB : )

The FB style has a few advantages, like trailing commas for instance. It's done this way to preserve git blame. It seemed weird when I first started there but I got used to it and it actually makes a big difference when you're looking at diffs that add one item to the end of the list (fairly often).

If you think it's weird on objects and arrays, it was even weirder when I first saw this:

``` javascript
export default function myFunctionWithLongName(
  firstArgument,
  secondArgument,
  thirdArgument,
) {
  // ...
}

// ... or the calling syntax ...

myFunctionWithLongName(
  firstArgument,
  secondArgument,
  thirdArgument,
}
```

Actually, that is now on track to be an ECMA standard (it's in some very mature stage) because it turns out to be great when you start putting trailing commas on every multi-line list (imagine using the sort-lines plugin in Atom and you don't have to mess with commas).

Speaking of things that might seem weird, this repo uses Flow, which when I first started using it felt like all the verbosity of Java was creeping into JS land. But it turns out this is extremely useful (although it will cause more of those multi-line function declarations like:

``` javascript
export default function myFunctionWithLongName(
  firstArgument: string,
  secondArgument: Array<Date>,
  thirdArgument: CustomClass,
): React.Element {
  // ...
}
```

Flow is extremely powerful because it:
- Helps catch errors you make much earlier (even more than you initially think)
- Helps you reason about the flow of data through your functions as you code (especially when teaching beginners, I find this pays off from day one).
- Self-documents your code for situations like when you go back after a month and you wonder, is this function expecting a Map of Date instances or an array of date strings?
- Implicitly discourages bad behaviors and encourages good ones (like making it much harder to do a constructor that takes two separate forms. You can go against the grain with some work, but you end up just making a static method to keep flow happy and make type annotations simple.)

I guess I got off topic there, but let's just say certain aspects of the FB coding style are super battle tested and chosen for good reasons. That being said, coding style is often very subjective and there's no more/less correct way for some preferences (unless you ask Douglas Crockford).

**Comment by sstur** [comment]
Closing this for now. In process of setting up a new monorepo. Will add Prettier for styling.
